# Generated by Django 4.0.4 on 2022-05-30 12:14

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to=images.models.user_directory_path)),
            ],
        ),
    ]
