# Generated by Django 3.2.16 on 2022-11-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='colorB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='images',
            name='colorG',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='images',
            name='colorR',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='images',
            name='tipeMakeUp',
            field=models.CharField(default='lips', max_length=50),
        ),
    ]
